COL OPID FORMAT 99999
COL STATUS FORMAT a11
COL ORIGIN FORMAT a20
COL COMPLETED FORMAT 99999
COL FAILED FORMAT 99999
COL TIMEOUT FORMAT 99999
COL INPROG FORMAT 99999

SELECT OPID, 
       ORIGIN, 
       STATUS, 
       TO_CHAR(START_TIME, 'DD/MM HH24:MI:SS') AS BEGIN_TIME,
       TO_CHAR(END_TIME, 'DD/MM HH24:MI:SS') AS END_TIME, 
       COMPLETED, 
       FAILED,
       TIMED_OUT AS TIMEOUT, 
       IN_PROGRESS AS INPROG
FROM DBA_AUTO_STAT_EXECUTIONS
ORDER BY OPID;