set echo off
set verify off
SET FEEDBACK OFF
COL BEGIN_INTERVAL_TIME FORMAT A20
COL END_INTERVAL_TIME FORMAT A20
COL SAMPLE_TIME FORMAT A19
COL PROGRAM FORMAT A40
COL SQL_ID FORMAT A13
col event format a18
COL SNAP_ID FORMAT 9999999
col inst_id format 99
COL IN_PARSE FORMAT A8
COL HD_PARSE FORMAT A8
COL SQL_EXEC FORMAT A8
COL PL_EXEC FORMAT A7
COL PL_COMP FORMAT A7
COL BLOCKING_SESS_STAT FORMAT A15
col BLK_sID format 99999 
col BLK_serial format 9999999
col program format a20
col machine format a20 
SET LINESIZE 300
SET PAGESIZE 80

ACCEPT SID PROMPT 'Sid  to monotoring --> '
ACCEPT SERIAL PROMPT 'Serial  to monotoring --> '

TTITLE  CENTER   "&SID - &SERIAL HISTORY" SKIP 2



BREAK ON SNAP_ID  SKIP 1



 SELECT SNAP_ID,
 INSTANCE_NUMBER inst_id ,
 CAST(SAMPLE_TIME AS DATE) SAMPLE_TIME,
 SESSION_TYPE,
 SQL_ID,
 SQL_PLAN_HASH_VALUE AS SPLAN_HASH,
 SQL_EXEC_START,
 EVENT,
 SESSION_STATE AS SESS_STAT,
 /*
 BLOCKING_SESSION_STATUS AS BLOCKING_SESS_STAT ,
 BLOCKING_session AS  BLK_sID,
 BLOCKING_session_serial# AS  BLK_SERIAL,
 */
 IN_PARSE IN_PARSE,
 IN_HARD_PARSE HD_PARSE,
 IN_SQL_EXECUTION SQL_EXEC,
 IN_PLSQL_EXECUTION PL_EXEC,
 IN_PLSQL_COMPILATION AS PL_COMP,
 SUBSTR(PROGRAM,1,20) PROGRAM,
 MACHINE,
 Round(PGA_ALLOCATEd/(1024*1024),2)MB_PGA_ALLOCATED 
 FROM DBA_HIST_ACTIVE_SESS_HISTORY
 WHERE SESSION_ID=&SID
 AND SESSION_SERIAL#=&SERIAL
 ORDER BY SNAP_ID,SAMPLE_TIME;
 

SET FEEDBACK ON

set verify on
TTITLE OFF
set echo on 